import { useState } from 'react';
import { motion } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { BackToHome } from '../components/BackToHome';

const faqs = [
  {
    question: 'How do I generate a color palette?',
    answer: 'Simply click the "Generate New Palette" button, and our algorithm will create a beautiful color combination for you. You can also choose how many colors you want (2-10) using the number selector above the palette.'
  },
  {
    question: 'Can I lock specific colors?',
    answer: 'Yes! Click the lock icon on any color card to lock it. When you generate a new palette, locked colors will remain unchanged while other colors are regenerated.'
  },
  {
    question: 'How do I export my palette?',
    answer: 'Click the "Export Palette" button below your palette. Your colors will be exported as a text file with all the hex codes. You can also copy individual colors by clicking the copy icon on each color card.'
  },
  {
    question: 'Is Paletize free to use?',
    answer: 'Yes! Paletize is completely free to use. You can generate unlimited color palettes without any restrictions or hidden fees.'
  },
  {
    question: 'Can I use these colors in commercial projects?',
    answer: 'Absolutely! All colors generated by Paletize are free to use in any project, including commercial ones. There are no licensing restrictions.'
  },
  {
    question: 'How many colors can I generate at once?',
    answer: 'You can generate between 2 and 10 colors in a single palette. Use the number selector to choose your preferred amount.'
  },
  {
    question: 'Do you save my palettes?',
    answer: 'No, we don\'t save your palettes. All color generation happens locally in your browser, ensuring your privacy and data security.'
  },
  {
    question: 'Can I share my palettes with others?',
    answer: 'Yes! You can copy the hex codes and share them, or export the palette file and send it to others. We\'re also working on a direct sharing feature.'
  }
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-900 py-24">
      <BackToHome />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h1 className="text-5xl font-bold text-gray-900 dark:text-white mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-400">
            Everything you need to know about Paletize
          </p>
        </motion.div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className="bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-gray-50 dark:hover:bg-slate-700 transition-colors"
              >
                <span className="text-lg font-semibold text-gray-900 dark:text-white pr-4">
                  {faq.question}
                </span>
                <ChevronDown
                  className={`w-5 h-5 text-indigo-600 dark:text-indigo-400 flex-shrink-0 transition-transform ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>
              {openIndex === index && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="px-6 pb-5"
                >
                  <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                    {faq.answer}
                  </p>
                </motion.div>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}


